baseurl = "https://www.seathaskymusic.com"
copyright = ""
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "Australia/Melbourne"
titlecasestyle = "Go"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "releases"
name = "Releases"
url = "/Releases"
weight = 20

[[languages.en.menu.main]]
identifier = "featured"
name = "Featured"
url = "/Featured"
weight = 30

[[languages.en.menu.main]]
identifier = "media showcase"
name = "Media Showcase"
url = "/media showcase"
weight = 40

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 50

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["html", "json", "rss"]

[params.paige.git]
commit_url = "https://github.com/willfaught/paige/commit/%s"